// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwLhLsYt_Oq4G0m_rvlO2izRkRU59BGs',
    appId: '1:132042967886:web:15a2fd44c243566365ac1f',
    messagingSenderId: '132042967886',
    projectId: 'chatapp-78252',
    authDomain: 'chatapp-78252.firebaseapp.com',
    storageBucket: 'chatapp-78252.firebasestorage.app',
    measurementId: 'G-RGSK15R73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu32Iz9UiaHq_OvvH0syjD2rh-8z6intU',
    appId: '1:132042967886:android:df186d2e1dde5ff265ac1f',
    messagingSenderId: '132042967886',
    projectId: 'chatapp-78252',
    storageBucket: 'chatapp-78252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNjtUWzPY5S2qLSYAkRq8O6S8_MogIXo',
    appId: '1:132042967886:ios:3488e5acc195e4ff65ac1f',
    messagingSenderId: '132042967886',
    projectId: 'chatapp-78252',
    storageBucket: 'chatapp-78252.firebasestorage.app',
    iosBundleId: 'com.example.frist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNjtUWzPY5S2qLSYAkRq8O6S8_MogIXo',
    appId: '1:132042967886:ios:3488e5acc195e4ff65ac1f',
    messagingSenderId: '132042967886',
    projectId: 'chatapp-78252',
    storageBucket: 'chatapp-78252.firebasestorage.app',
    iosBundleId: 'com.example.frist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIwLhLsYt_Oq4G0m_rvlO2izRkRU59BGs',
    appId: '1:132042967886:web:5f28fa8ad22a02d765ac1f',
    messagingSenderId: '132042967886',
    projectId: 'chatapp-78252',
    authDomain: 'chatapp-78252.firebaseapp.com',
    storageBucket: 'chatapp-78252.firebasestorage.app',
    measurementId: 'G-HZSH1CJFXR',
  );

}